### ISSUE TITLE
Too Minimal

### ISSUE THREAD

**Issue by soneji** [wdhg/wdhg.github.io#1]
# Please add fancy design to website, preferably with react or other bloated JavaScript  frameworks
![image](https://user-images.githubusercontent.com/12625848/89071715-2becef00-d36f-11ea-97a0-12b28d5c1adb.png)

# Please also consider using CSS
![image](https://user-images.githubusercontent.com/12625848/89071751-3c04ce80-d36f-11ea-8d35-96bc1f296562.png)

**Comment by wdhg** [comment]
not an issue
